language: ruby
rvm:
- 2.2.0
sudo: false
before_install:
  - gem install ruby_dep
script: JEKYLL_ENV=production bundle exec rake deploy
env:
  global:
    - secure: kgyFXw8IGR0YK3bLJ+4wIki3F0sZbZ34rvC4ZY1i9t58r7rduU3rz9rNOg72A365uItU305tHZQ3FZ7x2Z9Fd7Fe1YhSnz8uN+ZxKba80q89mGWfOFIo/j4i6D+TiDNl1oUtxJJiPspJLPUGcg9BSz/rntGRzp95nPh+KfyR7Zc174OCVxdGGdHVHDtSE8AxOQvxiv2Zq1xeERPlnxWH/7nhfybLeacY6S3YHK8mpTiOnNBT12tWgjHABimYcve5pcDAKeldNv+TUrvNFEe/DEQO4aRGJPrCK0o2FKNWBAdGaJihMPr3Mit6c5bm+CKbh0Z4tQFZeenpB/1L/0dOIHPxWVoGOyhX3UEJHhub2zaLjCShRMV9e1vjEnmVrPcXvYMgPebGXthz29PqZPh4rrMAdXnpv2JgDZ0suOXI1wdiAj3zFkCYXV3dPYSMPqyymS4b+7oXY+I0eA/GGxRL2kY2NnIWiOd2Ib+ADbxUTR6VaeXdUfFoNGb0PndYr86TDqbmRfERFu4n8rs7zurVkAf7OWNmu2XVJeTIc0XyUwp305ouueqw8kwe4gnPIQVzkkuYuyNVEi0hci4bdnNRIG9tMnyJdkIOu9Yznram9sXDe9R07LkwXZSBXzm6w2UwcBek+mlrfskRiON6LENXn06udznWlc+fUIf8HyIFyaU=
