# jekyll configuration

title: "Jekyll-asciidoc-quickstart"

gems:
  - jekyll-feed

# Not required when using a custom domain name
#baseurl: /blog

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

exclude: [tmp]
# end of configuration
