# jekyll configuration

title: "Jekyll-asciidoc-quickstart"

baseurl: /blog

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

exclude: [tmp]
# end of configuration
