# jekyll configuration

title: "I'm Lovin' I.T. - Julien Sobczak"

# Google Analytics
google_analytics: UA-111207061-1

# Metadata for feed
url: https://juliensobczak.com
author:
  name: Julien Sobczak

twitter_username: julien_sobczak

# Not required when using a custom domain name
# baseurl: /

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

exclude: [env, venv, tmp]
# end of configuration
