# jekyll configuration

title: "Jekyll-asciidoc-quickstart"
pygments: true

gems:
  - jekyll-asciidoc

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

# end of configuration
