---
layout: post-write
title: "Learn Programming Languages Like a Polyglot"
author: Julien Sobczak
date: '2017-06-06'
category: write
subject: Polyglot Programing
tags:
  - language
  - learning
  - productivity
---

==== Google Big Query "à la rescousse"

GitHub export its content in BigQuery. All repository contents (more than 3To) is available and open to analyzes: https://medium.com/@hoffa/400-000-github-repositories-1-billion-files-14-terabytes-of-code-spaces-or-tabs-7cfe0b5dd7fd[Spaces or Tabs], https://cloud.google.com/bigquery/public-data/github[Commonly used Go packages], or even https://medium.com/@hoffa/ed0e3011732c[run JHint on all JavaScript files]. The alleviate the 1To query limit when using the Free Tier on Google Cloud Platform, GitHub export the 400 000 top repositories (having at least 2 stars in the last months to be sure to exclude inactive repositories) in another tables:

* https://bigquery.cloud.google.com/table/bigquery-public-data:github_repos.sample_repos[`sample_repos`]: Name and URL of the repository
* https://bigquery.cloud.google.com/table/bigquery-public-data:github_repos.sample_files[`sample_files`]: All file metadata
* https://bigquery.cloud.google.com/table/bigquery-public-data:github_repos.sample_contents[`sample_contents`]: Some file metadata with the full content of non binary files.


The objective is to retrieve the most common methods/functions/objects. The SQL dialect supported by BigQuery is really extensive but not enough to parse the file content. For example, it is easy to extract the Go imported packages using a simple split and a regex like this:

.Most commonly used Go packages *(Source: https://cloud.google.com/bigquery/public-data/github)*
[source,sql]
----
SELECT
  REGEXP_EXTRACT(line, r'"([^"]+)"') AS url,
  COUNT(*) AS count
FROM
  FLATTEN( (
    SELECT
      SPLIT(SPLIT(REGEXP_EXTRACT(content, r'.*import\s*[(]([^)]*)[)]'), '\n'), ';') AS line,
    FROM (
      SELECT
        id,
        content
      FROM
        [bigquery-public-data:github_repos.sample_contents]
      WHERE
        REGEXP_MATCH(content, r'.*import\s*[(][^)]*[)]')) AS C
    JOIN (
      SELECT
        id
      FROM
        [bigquery-public-data:github_repos.sample_files]
      WHERE
        path LIKE '%.go'
      GROUP BY
        id) AS F
    ON
      C.id = F.id), line)
GROUP BY
  url
HAVING
  url IS NOT NULL
ORDER BY
  count DESC
LIMIT 10
----

But what if we need a list of functions with their respective packages. Let's take this basic example:

[source,go]
----
package main

import "net/http"
import "ioutil"

resp, err := http.Get("http://example.com/")
if err != nil {
	// handle error
}
defer resp.Body.Close()
body, err := ioutil.ReadAll(resp.Body)
----

Three methods are called:

----
+---------------+-----------------+
| Package       | Function/Method |
+---------------+-----------------+
| net/http      | Get             |
| io.ReadCloser | Close           |
| ioutil        | ReadAll         |
+---------------+-----------------+
----

How to extract this result using only regular expressions? We can't. The good news is BigQuery support User-Defined Functions (UDF), which allow us to parse any field combination using a custom JavaScript snippet. This feature is describe extensively https://cloud.google.com/bigquery/user-defined-functions[here]. We can also use the http://storage.googleapis.com/bigquery-udf-test-tool/testtool.html[UDF test tool] to test and debug our UDF without running up our BigQuery bill.
