== What happens when you install a package using `apt`

The major reason to use `apt` is for the dependency management support. This command understands that in order to install a given package, other packages may need to be installed too, and `apt` can download these and install them, whereas `dpkg` cannot. In practice, `dpkg` is called a package manager whereas `apt` is called a frontend package manager.

[NOTE]
.What You Need to Know About `apt`, `apt-get`, `aptitude`?
====
APT is a vast project started in 1997 organized around a core library. The command `apt-get` was the first frontend developed within the project, and `apt` is the second command provided by APT which overcomes some design mistakes of `apt-get`, for example,  `apt` refuse to install dependencies which were not installed beforehand during an upgrade. Under the hood, both tools are built on top of this core library and are thus very close.

Externals similar projects like `aptitude` have been developed later (in 1999 for aptitude) to support new features like auto-removing packages when no longer required, a feature now available in Apt too.

The most widespread command remains `apt`, and it is the one that we will use in this section.

* Apt (`apt` and `apt-get`) Official Repository: https://salsa.debian.org/apt-team/apt
* Apt GitHub Mirror: https://github.com/Debian/apt
* Aptitude Official Repository: https://salsa.debian.org/apt-team/aptitude

_Further documentation_: link:https://raphaelhertzog.com/2011/06/20/apt-get-aptitude-%e2%80%a6-pick-the-right-debian-package-manager-for-you/[apt-get, aptitude, … pick the right Debian package manager for you, Raphaël Hertzog]
====

APT makes software available to the user and does the dirty work of downloading all the required packages and installing them by calling dpkg in the correct order to respect the dependencies.

APT is written in C++. The entry point for any APT command is the file `cmdline/apt.cc` which contains a function `GetCommands()` that maps each command with a function defined in the directory `apt-private/`, which delegates to other functions in the main APT lib present in the directory `apt-pkg/` (cmdline/ -> apt-private/ -> apk-pkg/):

[source,c++]
.cmdline/apt.cc
----
static std::vector<aptDispatchWithHelp> GetCommands()                        /*{{{*/
{
   return {
      // query
      {"list", &DoList, _("list packages based on package names")},

      // package stuff
      {"install", &DoInstall, _("install packages")},

      // system wide stuff
      {"update", &DoUpdate, _("update list of available packages")},

      // ...

      {nullptr, nullptr, nullptr}
   };
}
----

Before invoking the command function, APT initializes a few classes like `pkgSystem` to define the default configuration settings. and supports many commands.

=== Prerequisites

Let's recreate a new VM and list the installed packages on it:

[source,sh]
----
$ vagrant destroy
$ vagrant up
$ vagrant ssh

vagrant$ apt list
adduser/now 3.118 all [installed,local]
apparmor/now 2.13.6-9 amd64 [installed,local]
apt-listchanges/now 3.23 all [installed,local]
apt-utils/now 2.1.20 amd64 [installed,local]
apt/now 2.1.20 amd64 [installed,local]
base-files/now 11 amd64 [installed,local]
base-passwd/now 3.5.49 amd64 [installed,local]
bash-completion/now 1:2.11-2 all [installed,local]
…
----

[NOTE]
.What You Need to Know About APT configuration?
====
APT configuration resides under `/etc/apt/` which includes the following files:

* `apt.conf` and `apt.conf.d/`: The main configuration files where hundred of settings are available. The command `apt-config dump` can be used to view all available settings with their default values:
+
[source,sh]
----
$ apt-config dump
...
Dir "/";
Dir::State "var/lib/apt";
Dir::State::status "/var/lib/dpkg/status";
Dir::Cache "var/cache/apt";
Dir::Etc "etc/apt";
Dir::Etc::sourcelist "sources.list";
Dir::Etc::sourceparts "sources.list.d";
Dir::Etc::main "apt.conf";
Dir::Etc::parts "apt.conf.d";
Dir::Etc::preferences "preferences";
Dir::Etc::preferencesparts "preferences.d";
Dir::Etc::trusted "trusted.gpg";
Dir::Etc::trustedparts "trusted.gpg.d";
...
----
* `sources.list` and `sources.list.d/`: lists of software repositories. See the next panel link:TODO[What You Need to Know About APT repositories]. Here are the default repositories on my Debian server:
+
[source,sh]
----
$ cat /etc/apt/sources.list
deb http://deb.debian.org/debian bullseye main
deb-src http://deb.debian.org/debian bullseye main
deb http://security.debian.org/debian-security bullseye-security main
deb-src http://security.debian.org/debian-security bullseye-security main
deb http://deb.debian.org/debian bullseye-updates main
deb-src http://deb.debian.org/debian bullseye-updates main
deb http://deb.debian.org/debian bullseye-backports main
deb-src http://deb.debian.org/debian bullseye-backports main
----
* `preferences` and `preferences.d/`: APT pinning is the only available preference. By default, when multiple repositories are configured, a package can exist in several of them and APT applies logic to decide which one must be installed. Pinning allows you to change this logic called a policy for some packages. The command `apt-cache policy [pkg]` can be used to view the global policy when called without argument`:
+
[source,sh]
----
$ apt-cache policy
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://security.debian.org/debian-security bullseye-security/main amd64 Packages
     release o=Debian,a=testing-security,n=bullseye-security,l=Debian-Security,c=main,b=amd64
     origin security.debian.org
 500 http://deb.debian.org/debian bullseye/main amd64 Packages
     release o=Debian,a=testing,n=bullseye,l=Debian,c=main,b=amd64
     origin deb.debian.org
----
+
You can create preferences files to privilege a specific repository for a given package or to prevent this package to be upgraded.
* `trusted.gpg` and `trusted.gpg.d/`: keys for secure authentication of packages (known as "Secure APT" and used in Debian since 2005). The command `apt-key` can be used to show the keys, and to add or remove a key. APT uses public-key (asymmetric) cryptography using GPG:
+
[source,sh]
----
$ ls -1 /etc/apt/trusted.gpg.d/
debian-archive-bullseye-automatic.gpg
debian-archive-bullseye-security-automatic.gpg
debian-archive-bullseye-stable.gpg
debian-archive-buster-automatic.gpg
debian-archive-buster-security-automatic.gpg
debian-archive-buster-stable.gpg
debian-archive-stretch-automatic.gpg
debian-archive-stretch-security-automatic.gpg
debian-archive-stretch-stable.gpg
----
+
When installing a package, APT retrieves the package from an external repository and the `Release` file, which is the entry file to find `Packages` index files, may have be altered (which means checking the MD5 sums inside these index files is useless if we can't guarantee that the `Release` file is safe against a man-in-the-middle attack). This is the goal of secure APT. Concretely, secure APT always downloads a `Release.gpg` file if existing before downloading a `Release` file (since, the file `InRelease` had now merged the intent of these two deprecated files). Using cryptography, APT can be sure the file is safe and can trust the MD5 sums present inside the file to check `Packages` files. If APT cannot guarantee the repository identity, it will complain with the following messages you have probably already encountered:
+
[source,sh]
----
# When adding a new repository in `/etc/apt/sources.list.d/`:
W: GPG error: http://ftp.us.debian.org testing Release: The following signatures
 couldn't be verified because the public key is not available: NO_PUBKEY 010908312D230C5F
# When installing a new package from this repository:
WARNING: The following packages cannot be authenticated!
  libglib-perl libgtk2-perl
Install these packages without verification [y/N]?
----
* `auth.conf` and `auth.conf.d/`: APT configuration and repositories list must be accessible to any user on the system but some repositories may require login information to connect, which are stored in these restrictive files. For example, instead of specifying the user/password `apt:debian` in the source list file directly (`deb https://apt:debian@example.org/debian buster main`), you can create an entry in `auth.conf`:
+
[source]
----
machine example.org
login apt
password debian
----
* `listchanges.conf` and `listchanges.conf.d`: Only used by the command `apt-listchanges` to show what has been changed in a new version of a Debian package, as compared to the version currently installed on the system. It does this by extracting the relevant entries from both the `NEWS.Debian` and `changelog[.Debian]` files, usually found in `/usr/share/doc/_package_` in Debian package archives. _(not covered in this article)_

In practice, `.d` directories (also called dot-dee directories) are privileged so that the configuration can be split into several files. Single file may not even exist and are deprecated.

_Further documentation_: link:https://wiki.debian.org/AptConfiguration[APT configuration], link:https://wiki.debian.org/SecureApt[Secure APT].
====

[NOTE]
.What You Need to Know About APT configuration
====
Unlike Dpkg, APT is highly configurable. The main file was historically `/etc/apt/apt.conf`and this file is still read if it exists, but nowadays, the configuration is split in separate files in `/etc/apt/apt.conf.d/` so that it can be added and updated independent of any local changes you make in the main configuration file. You can also use the `APT_CONFIG` environment variable to specify another directory.

The format used by APT is a specific format similar to other Linux tools like `bind` or `dhcp`.

[source,sh]
----
vagrant$ cat /etc/apt/apt.conf.d/*
APT
{
  NeverAutoRemove
  {
	"^firmware-linux.*";
	"^linux-firmware$";
	"^linux-image-[a-z0-9]*$";
	"^linux-image-[a-z0-9]*-[a-z0-9]*$";
  };
};
DPkg::Pre-Install-Pkgs { "/usr/bin/apt-listchanges --apt || test $? -lt 10"; };
...
----
The configuration file is organized in a tree organized into functional groups. For instance, `APT::Get::Assume-Yes` is an option within the `APT` tool group, for the `Get` tool. A new scope can be opened with curly braces, like this:

[source]
----
APT {
  Get {
    Assume-Yes "true";
    Fix-Broken "true";
  };
};
----

You can retrieve the full list of options using the command `apt-config`:

[source,sh]
----
vagrant# apt-config dump
APT "";
APT::Architecture "amd64";
APT::Build-Essential "";
APT::Build-Essential:: "build-essential";
APT::Install-Recommends "1";
APT::Install-Suggests "0";
APT::Sandbox "";
APT::Sandbox::User "_apt";
… hundreds of other options ...
----

Inside the code, configuration is accessible using the class `Configuration` (defined in `apt-pkg/contrib/configuration.h`):

[source,c++]
----
#include <apt-pkg/configuration.h>

Configuration *_config = new Configuration;

// Example with a boolean option
if (_config->FindB("pkgCacheFile::Generate", true) == false) {}

// Example with an integer option
int const Limit = _config->FindI("Acquire::QueueHost::Limit",DEFAULT_HOST_LIMIT)
----

_Further documentation_: link:https://www.commandlinux.com/man-page/man5/apt.conf.5.html[man page]
====


[NOTE]
.What You Need to Know About Source Lists
====
Apt downloads packages from one or more software repositories, which are often remote servers. The precise list of repositories is determined by the files `/etc/apt/sources.list` and the ones inside `/etc/apt/sources.list.d`. Two formats are supported: one source per line (the widespread one-line style) or multiline stanzas defining one or more sources per stanza (the newer deb822 style).

Ex using the old format:

[source]
----
deb http://us.archive.ubuntu.com/ubuntu focal main restricted
deb http://security.ubuntu.com/ubuntu focal-security main restricted
deb http://us.archive.ubuntu.com/ubuntu focal-updates main restricted
----

Ex using the new format:

[source,deb822]
----
Types: deb
URIs: http://us.archive.ubuntu.com/ubuntu
Suites: focal focal-updates
Components: main restricted

Types: deb
URIs: http://security.ubuntu.com/ubuntu
Suites: focal-security
Components: main restricted
----

I'm running my code on a Ubuntu 20.04, which still uses the old widespread format. I will ignore the new DEB 822 format in this article. For more information about the repository, check the note link:TODO[What You Need To Know About Repositorie]

*Further documentation*: link:http://manpages.ubuntu.com/manpages/focal/man5/sources.list.5.html[man 5 sources.list]
====

[NOTE]
.What You Need to Know About Repositories
====
A repository is a set of Debian binary or source packages organized in a special directory tree along various additional files--checksums, signatures, translations, ... APT downloads some these files to install a package on your system.

Ex: `deb https://deb.debian.org/debian stable main contrib non-free`

* `deb` is used for *binary packages*, `deb-src` for *source packages*.
* `https://deb.debian.org/debian` specifies the root of the *repository*.
* `stable` is the distribution, which is commonly a *suite* (`stable`, `oldstable`, `testing`, `unstable`), which are alias to Debian *codenames* (`wheezy`, `jessie`, `stretch`), which are based on Toy Story characters.
* `main contrib non-free` are the three *component* types and indicate the licensing terms of the software they contain.

Here is a preview of files tree for this repository:

[source]
----
https://deb.debian.org/debian
└── dists/
    |── Debian9.13/
    |── Debian10.9/
    |   ├── ChangeLog
    |   ├── InRelease # Same as Release + Release.gpg (recommended to have only 1 file to download)
    |   ├── Release   # Lists the index files for this distribution with their hashes
    |   ├── Release.gpg
    |   ├── contrib/
    |   ├── main/
    |   │   └── binary-all/
    |   │   |   |── Packages.gz
    |   │   |   |── Packages.xz # Several compression formats are accepted.
    |   |   |   |               # xz compression is required.
    |   │   |   |── Release # Basic metadata about this directory.
    |   |   |   |           # Not comparable with the main Release file.
    |   │   |── binary-amd64/
    |   │   |── ...
    |   │   |── content-all.gz   # Index containing for the list of all files in package archives
    |   │   |── content-amd64.gz # and their corresponding package archive.
    |   │   |── ...
    |   |   |── i18n/ # Translations of Packages files
    |   |   └── source/
    |   │       |──  Release
    |   │       |──  Sources.gz
    |   │       |──  Sources.xz
    |   └── non-free/
    |── bullseye/ # Future Debian 11
    |── buster/   # Symlink to Debian10.9
    |── stable/   # Symlink to buster
    |── stretch/  # Symlink to Debian9.13
    └── testing/  # Symlink to bullseye
----

And now the explanations.

The root directory contains a directory `dists/` which in turn has a directory for each release and suite, the latter usually symlinks to the former. Each release subdirectory contains a signed `Release` file and a directory for each component. Inside these are directories for the different architectures, named `binary-<arch>` and `sources`. And in these are files `Packages` and `Sources` that are text files (in DEB 822 format and often compressed) containing the meta data of packages.

[source]
.http://ftp.debian.org/debian/dists/Debian10.9/main/binary-amd64/Packages.gz
----
# 57849 binary packages declarations like this:
Package: wget
Version: 1.20.1-1.1
Installed-Size: 3257
Maintainer: Noël Köthe <noel@debian.org>
Architecture: amd64
Depends: libc6 (>= 2.28), libgnutls30 (>= 3.6.6), libidn2-0 (>= 0.6), libnettle6, libpcre2-8-0 (>= 10.32), libpsl5 (>= 0.16.0), libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4)
Recommends: ca-certificates
Conflicts: wget-ssl
Description: retrieves files from the web
Multi-Arch: foreign
Homepage: https://www.gnu.org/software/wget/
Description-md5: 63a4a740bcd9e8e94bf661e4f1806e02
Tag: implemented-in::c, interface::commandline, network::client,
 protocol::ftp, protocol::http, protocol::ssl, role::program,
 suite::gnu, use::downloading, works-with::file
Section: web
Priority: standard
Filename: pool/main/w/wget/wget_1.20.1-1.1_amd64.deb
Size: 901956
MD5sum: a7e3faa711503bd9500650de8fc9835e
SHA256: 3821cee0d331cf75ee79daff716f9d320f758f9dff3eaa6d6cf12bae9ef14306

Package: libwget0
Source: wget2
Version: 1.99.1-2
Installed-Size: 387
Maintainer: Noël Köthe <noel@debian.org>
Architecture: amd64
Depends: libassuan0 (>= 2.0.1), libbrotli1 (>= 0.6.0), libbz2-1.0, libc6 (>= 2.27), libgnutls30 (>= 3.5.10), libgpg-error0 (>= 1.14), libgpgme11 (>= 1.1.2), libidn2-0 (>= 0.6), liblzma5 (>= 5.1.1alpha+20120614), libnghttp2-14 (>= 1.3.0), libpcre2-8-0 (>= 10.31), libpsl5 (>= 0.16.0), zlib1g (>= 1:1.1.4)
Description: Download library for files and recursive websites
Homepage: https://gitlab.com/gnuwget/wget2
Description-md5: 3cb4ed03cbc78579a7e509e41156a73f
Tag: role::shared-lib
Section: libs
Priority: optional
Filename: pool/main/w/wget2/libwget0_1.99.1-2_amd64.deb
Size: 146028
MD5sum: 944b2824ee264e1b0cc0f91c1a86e6e2
SHA256: 3bf97e4852e76dba5bf2261f4a949a445edda646d09d7d1175dccfdf77bdbc3f
----

And

[source]
.http://ftp.debian.org/debian/dists/Debian10.9/main/source/Sources.gz
----
# 28489 source packages declarations like this:
Package: wget
Binary: wget, wget-udeb
Version: 1.20.1-1.1
Maintainer: Noël Köthe <noel@debian.org>
Build-Depends: debhelper (>> 11.0.0), pkg-config, gettext, texinfo, libidn2-0-dev, uuid-dev, libpsl-dev, libpcre2-dev, libgnutls28-dev (>= 3.3.15-5), automake, libssl-dev (>= 0.9.8k), zlib1g-dev, dh-strip-nondeterminism
Architecture: any
Standards-Version: 4.3.0
Format: 3.0 (quilt)
Files:
 7a84dd8efb09001dcb9af1576b35992c 2092 wget_1.20.1-1.1.dsc
 f6ebe9c7b375fc9832fb1b2028271fb7 4392853 wget_1.20.1.orig.tar.gz
 e0ed66f143f4d81dd0f27a8f01a9c5c8 60872 wget_1.20.1-1.1.debian.tar.xz
Checksums-Sha256:
 b193fdf37cc33955e366ae1fdb6df5425d13769d9e131c52382ae132ad931261 2092 wget_1.20.1-1.1.dsc
 b783b390cb571c837b392857945f5a1f00ec6b043177cc42abb8ee1b542ee1b3 4392853 wget_1.20.1.orig.tar.gz
 7eee4b6b9394a495888d1fc0db951c6b3bd883ca522a11df3433732dc116001e 60872 wget_1.20.1-1.1.debian.tar.xz
Homepage: https://www.gnu.org/software/wget/
Package-List:
 wget deb web standard arch=any
 wget-udeb udeb debian-installer optional arch=any
Directory: pool/main/w/wget
Priority: source
Section: web
----

But still no `.deb` packages... We need to move to another directory at the root of the repository:

[source]
----
https://deb.debian.org/debian
└── dists/
    |── contrib/
    |── main/
    |   |── 0/
    |   |── 1/
    |   |── ...
    |   |── 9/
    |   |── a/
    |   |── ...
    |   |── w/
    |       |── ....
    |       └── wget/
    |   |── ...
    |   |── z/
    |   |── liba/
    |   |── ...
    |   |── libw/
    |   |   |── wget_1.21-1+b1_amd64.deb
    |   |   |── wget_1.21-1.debian.tar.xz
    |   |   |── wget_1.21-1.dsc
    |   |   |── wget_1.21-1_arm64.deb
    |   |   |── wget_1.21.orig.tar.gz
    |   |   └── wget_1.21.orig.tar.gz.asc
    |   |── ...
    |   └── libz/
    └── non-free/
----

The directory `pool/` has a directory for all the components, and in these are directories named `0`, ..., `9`, `a`, ... `z`, `liba`, ... , `libz`. And in these are directories named after the software package they contain, and these directories finally contain the actual packages, i.e the `.deb` files.

Notes:
* The "single letter" directories are just a trick to avoid having too many entries in a single directory which is what many systems traditionally have performance problems with.
* The `pool/` directory avoid file duplication as binary and source packages are stored only once even if used by many releases under `dists/`.
* `Packages` and `Sources` index files are control files using a similar format as used in the first part of this article when creating our Debian archive package, with a special field `File` and `Directory` respectively, to link to the `pool/`.
* `Release` is an index file in the DEB822 format but contains a single document whose field names refers to the repository -- `Origin`, `Suite`, `Codename`, `Architectures` (plural), `Components` -- and whose field `MD5Sum` contains the checksums for all files in this repository.

*Further documentation*: link:https://wiki.debian.org/DebianRepository[Debian Repository] and the more complete link:https://wiki.debian.org/DebianRepository/Format[Repository Format]
====

[NOTE]
.What You Need to Know About APT Diffs
====
`Packages` files (and also some other indices files present in a Debian repository) can be relatively large. For example, the compressed `Package.xz` file for the architecture`amd64` and the component `main` of the stable Debian repository weights 8 MB. These files are typically retrieved when you run the command `apt update` and APT provides a solution to this problem.

Indeed, a Debian repository can contains diff files (whose content are similar to the output of the command `diff`) along the standard files like `Packages`:

[source]
----
https://deb.debian.org/debian
└── dists/bullseye/main/binary-amd64
    |── Packages.xz  7.8M
    └── Packages.diff/
        |── ... # The Debian official repository keeps ~30 days of diff files.
        |── 2021-04-12-1400.57.gz        33
        |── 2021-04-13-0200.48.gz        7.8K
        |── 2021-04-13-1402.06.gz        637
        |── 2021-04-13-2000.50.gz        660
        |── 2021-04-14-0200.40.gz        2.7K
        |── 2021-04-14-2000.54.gz        5.0K
        |── 2021-04-15-0200.39.gz        3.8K
        └── 2021-04-15-1400.39.gz        220
----

The `apt` command will try to retrieve these files and apply successives diffs on top of its previous index.
====

[NOTE]
.What You Need to Know About /var/lib/apt/
====

The directory stores the current state of APT, that is which packages have been installed, what is the last known version of the main index files of every repository in the list of sources, etc.

[source,sh]
----
$ tree /var/lib/apt/
.
|-- daily_lock  # Used by the Systemd apt-daily.timer for housekeeping tasks.
|               # Runs /usr/lib/apt/apt.systemd.daily which clean the cache,
|               # update the repositories, create backups of extended_states...
|-- extended_states # Extension to /var/lib/dpkg/status to store which packages were
|                   # installed manually or automatically (i.e., as a dependency of another
|                   # package). Useful to support autoremove of useless packages.
|-- listchanges.db # Used by the command apt-listchanges not covered in this article.
|-- lists # Local version of index files retrieves from repositories in sources.list
|   |-- deb.debian.org_debian_dists_bullseye-backports_InRelease
|   |-- deb.debian.org_debian_dists_bullseye-updates_InRelease
|   |-- deb.debian.org_debian_dists_bullseye_InRelease
|   |-- deb.debian.org_debian_dists_bullseye_main_binary-amd64_Packages
|   |-- deb.debian.org_debian_dists_bullseye_main_binary-amd64_Packages.diff_Index
|   |-- deb.debian.org_debian_dists_bullseye_main_i18n_Translation-en
|   |-- deb.debian.org_debian_dists_bullseye_main_i18n_Translation-en.diff_Index
|   |-- deb.debian.org_debian_dists_bullseye_main_source_Sources
|   |-- deb.debian.org_debian_dists_bullseye_main_source_Sources.diff_Index
|   |-- lock  # Same as /var/lib/dpkg/lock. Prevent two processes to use the lib APT at the same time
|   |-- partial/  # Storage area for index files in transit
|   |-- security.debian.org_debian-security_dists_bullseye-security_InRelease
|   |-- security.debian.org_debian-security_dists_bullseye-security_main_binary-amd64_Packages
|   |-- security.debian.org_debian-security_dists_bullseye-security_main_i18n_Translation-en
|   `-- security.debian.org_debian-security_dists_bullseye-security_main_source_Sources
|-- mirrors  # Used when using repository mirrors. Not covered in this article.
|   `-- partial
`-- periodic  # Empty files whose timestamps are updated by the Systemd apt-daily.timer
    |         # to determine the last timer execution date.
    |-- download-upgradeable-stamp
    |-- unattended-upgrades-stamp
    |-- update-stamp
    `-- upgrade-stamp
----

This directory doesn't have to be edited like `/etc/apt/` and doesn't have to be cleaned like '/var/cache/apt/'. It can be safely ignored even if you are going to talk about it in this article as we are looking under the hood of APT.
====


include::./part-3-update.adoc[]
include::./part-3-list.adoc[]
include::./part-3-install.adoc[]


Like for other parts, we are going to summarize what we learned by reimplementing a basic version of the command `apt install` in Go. We will not bother with a cache and simply read the Debian repositories.

To test our program, we need a basic package so that we can focus on the main parts of the APT installation process.

We will use a new version of our hello package (the code is available in the link:TODO[companion GitHub repository]):

[source,sh]
----
vagrant# tree /vagrant/hello/3.1-1/
3.1-1/
|-- DEBIAN
|   `-- control
`-- usr
    `-- bin
        `-- hello

vagrant# cat /vagrant/hello/3.1-1/DEBIAN/control
Package: hello
Version: 3.1-1
Section: base
Priority: optional
Architecture: amd64
Maintainer: Julien Sobczak
Description: Say Hello
Depends: cowsay # <1>

vagrant# cat /vagrant/hello/3.1-1/usr/bin/hello
#!/bin/bash
echo "hello world" | /usr/games/cowsay # <2>
----
<1> Declare a required dependency available from standard Debian repository.
<2> Use the binary installed by this dependency.

To build the new package:

[source,sh]
----
vagrant# $ dpkg-deb --build -Z none 3.1-1 hello_3.1-1_amd64.deb
----

Example of installation using APT:

[source,sh]
----
vagrant# apt install /vagrant/hello/hello_3.1-1_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'hello' instead of '/vagrant/hello/hello_3.1-1_amd64.deb'
The following additional packages will be installed:
  cowsay
Suggested packages:
  filters cowsay-off
The following NEW packages will be installed:
  cowsay hello
0 upgraded, 2 newly installed, 0 to remove and 11 not upgraded.
After this operation, 94.2 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y

Get:1 /vagrant/hello/hello_3.1-1_amd64.deb hello amd64 3.1-1 [20.7 kB]
Get:2 http://deb.debian.org/debian bullseye/main amd64 cowsay all 3.03+dfsg2-8 [21.4 kB]
Fetched 21.4 kB in 0s (66.6 kB/s)
Selecting previously unselected package cowsay.
(Reading database ... 34384 files and directories currently installed.)
Preparing to unpack .../cowsay_3.03+dfsg2-8_all.deb ...
Unpacking cowsay (3.03+dfsg2-8) ...
Selecting previously unselected package hello.
Preparing to unpack .../hello/hello_3.1-1_amd64.deb ...
preinst says hello
Unpacking hello (3.1-1) ...
Setting up cowsay (3.03+dfsg2-8) ...
Setting up hello (3.1-1) ...
postinst says hello
Processing triggers for man-db (2.9.4-2) ...

vagrant# hello
 _____________
< hello world >
 -------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
----

The challenge is to install the same package using a basic Go program. We will reuse the dpkg version we wrote in Go.

Here is the code:

[source,go]
.main.go
----
include::apt_install.go[]
----

That's it. We created a Debian archive using a basic Go program and we install the package using basic Dpkg and APT versions also written in Go.

